/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersLeaderboardRouteImport } from './routes/workers-leaderboard'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const WorkersLeaderboardRoute = WorkersLeaderboardRouteImport.update({
  id: '/workers-leaderboard',
  path: '/workers-leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/workers': typeof WorkersRoute
  '/workers-leaderboard': typeof WorkersLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/workers': typeof WorkersRoute
  '/workers-leaderboard': typeof WorkersLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/workers': typeof WorkersRoute
  '/workers-leaderboard': typeof WorkersLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/reports' | '/workers' | '/workers-leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/reports' | '/workers' | '/workers-leaderboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reports'
    | '/workers'
    | '/workers-leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  WorkersRoute: typeof WorkersRoute
  WorkersLeaderboardRoute: typeof WorkersLeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers-leaderboard': {
      id: '/workers-leaderboard'
      path: '/workers-leaderboard'
      fullPath: '/workers-leaderboard'
      preLoaderRoute: typeof WorkersLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  WorkersRoute: WorkersRoute,
  WorkersLeaderboardRoute: WorkersLeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
